### ISSUE TITLE
jTidy fails with Null pointer exception incase of white space  before <br> 

### ISSUE THREAD

**Issue by sirsusar** [jtidy/jtidy#32]
Hi , 

I'm using jTidy version 1.0.2 and here is my configuration set up 

        Tidy tidy = new Tidy();
         tidy.setInputEncoding("UTF-8");
         tidy.setOutputEncoding("UTF-8");
         tidy.setForceOutput(true);
         tidy.setWrapSection(false);
         tidy.setWraplen(0);
         tidy.setShowErrors(0);
         tidy.setShowWarnings(false);
         tidy.setEscapeCdata(true);
         tidy.setFixComments(true);
         tidy.setIndentCdata(true);
         tidy.setDropProprietaryTags(true);

Few  of my html  documents fail when I try parsing them using jTidy  and after debugging I found that it was space before <br> that is causing the issue .  Is there anyway I can handle  this whitespace please advice ?

Here is the error from console 
Exception in thread "main" java.lang.NullPointerException
	at org.w3c.tidy.PPrint.afterSpace(PPrint.java:1358)
	at org.w3c.tidy.PPrint.afterSpace(PPrint.java:1366)
	at org.w3c.tidy.PPrint.printTag(PPrint.java:1423)
	at org.w3c.tidy.PPrint.printTree(PPrint.java:2209)
	at org.w3c.tidy.PPrint.printTree(PPrint.java:2306)
	at org.w3c.tidy.PPrint.printTree(PPrint.java:2363)
	at org.w3c.tidy.PPrint.printTree(PPrint.java:2363)
	at org.w3c.tidy.PPrint.printTree(PPrint.java:2363)
	at org.w3c.tidy.PPrint.printTree(PPrint.java:2363)
	at org.w3c.tidy.PPrint.printTree(PPrint.java:2152)

**Comment by haumacher** [comment]
Can you please attach the HTML source code that causes the error?

**Comment by haumacher** [comment]
Can you please attach the HTML source code that causes the error?
